Update scp-transfer
This is a script I wrote to efficiently manage file transfers - and I picked rsync as it is the file transfer method of choice when an administrator is seeking a solution that is fast, secure and reliable. In addition rsync gives administrators an answer of what to use given the deprecation of scp as a secure protocol considering Red Hat's advice to avoid it - and there is at least one CVE which speaks to that advice. I am in agreement with it.  

This script is not perfect and the wildcards I am using do not selectively sort out files by name - and for that reason, while it is great for personal use, without some tweaking it should not be used hardcore in production environments. While it is safe, I am not done perfecting it and there are some features it lacks. I will be rewriting this in likely Go or Python. You could also do something very cool by using Ruby or Perl - and given Perl's nature of handling RegEx and its ties to the Unix/Linux tradition, it would be a great language to use.

diff --git a/scp-transfer b/scp-transfer
--- a/scp-transfer
+++ b/scp-transfer
@@ -1,62 +1,89 @@
-#!/bin/bash
-#NOTE: For this to work, you need a file which includes programs - binary or otherwise - that need to be transfered... This file will be a list. To parse the list
-#This script was intended to be highly customizable. If you have a unique files structure in your target host, you will have to address that issue accordingly when 
-#implementing this script. 
+#!/bin/bash 
 
-#populate file list first - and you can create a function for this long bash one-liner: 
-# find $HOME/dirpath -type f |  sed 's|^~/bin/||' | tr '\0' '\n' | tee /dirpath/filelist.txt
-#As a function in .bashrc, you can always do this: 
 
-#function cutlead {
-#   sed 's|^./||' | tr '\0' '\n'  
-#}
+#Aug 23, 2023 
+#NOTE: This is current set up for a list and that's what filearg is for now 
 
-#Accurately, you also need to run another command ... and I will include more code for that if needed. 
-#You could do something as simple as ls dirpath | sed 's|^~/bin/||' ... At least on a Linux system, leading characters of ./ are not good friends of our dear SCP 
-#command and if you populate a list by cancatenating files using the good ol' tee command with say find as a pipe - very bad things will happen and those are not 
-#good things which are also bad. In short - it won't work ... 
-
-#the files must be parsed onto a list without a trailing < ./ > - or else running the script #against files on a list in any other form will result in imminent #failure 
-#As of now, this is limited ... It should work with pretty much any object a sys admin or end user is trying to fetch but I mostly use it for smaller files 
-#This has not been tested thoroughly but it is stable or has shown itself to be and I find it mighty handy - if I don't say so myself. Hopefully you enjoy it #whomever you are
-
-if [[ $1 = "-h" ]]; then
-    echo "Options: scp-transfer filelist.txt localdir"
-elif [[ $# -lt 2 ]]; then 
-    echo "Two arguments are required for this script:"
-    echo "Options: scp-transfer filelist.txt localdir"
-else
-    keyfile="/home/username/.ssh/id_rsa"
-    filelist="$1"
-    targetdir="$2" # local directory - where files go 
-    hostarget="domain:dirpath/"
-
-    # Read the filelist into an array
-    readarray -t files_to_transfer < "$filelist"
-
-    # Array to store filenames already processed
-    processed_files=()
-
-    # Iterate through the files in the target directory
-    for filename in "${files_to_transfer[@]}"; do
-        # Check if the file has been processed before
-        if [[ " ${processed_files[*]} " == *" $filename "* ]]; then
-            echo "File already processed. Skipping: $filename" | tee -a ~/tmp/scp-transfer.log
-            continue
-        else
-            # Add the filename to the processed_files array
-            processed_files+=(" $filename ")
-
-            # Wrap the filename in double quotes
-            quoted_filename="$(printf "%q" "$filename")"
-
-            if scp -i "$keyfile" -r "$hostarget$quoted_filename" "$targetdir"; then
-                echo "Successfully transferred file: $filename" | tee -a ~/tmp/scp-transfer.log
-            else
-                echo "Failed to transfer file: $filename" | tee -a ~/tmp/scp-transfer.log
-            fi
-        fi
-    done
-
+if [[ -z "${1}" ]]; then
+    echo "Error: missing an argument. Enter a file"
+    echo Ex: \"rsync-download file\"
+    exit 1
+elif [[ "${1}" == "-h" ]]; then
+   echo "Enter a filelist to process"
+   echo Ex: \"rsync-download file\"
+   exit 0
 fi
+
+
+
+
+
+
+
+logloc="${HOME}/tmp/rsync-download.log"
+server="username@domain-url:dir"
+filearg="${1}"
+
+filecmd=$(du -hs /home/username/medianame")
+trimcalc=$(echo "${filecmd}" | awk '{print $1}' | sed 's/K//g' |  sed 's/G//g') || true    
+reducedval=$(echo "${filecmd}" | awk '{print $1}' | sed 's/K//g' |  sed 's/G//g' | sed 's/M//g') || true 
+
+
+val="$trimcalc"
+#echo "$val"
+
+charval="$reducedval"
+output="${val: -1}"
+
+charmax() {
+   ${charval}  
+   n=0
+   while read -n1 character; do 
+   n=$((n+1))
+   done < <(echo -n "${charval}")
+   echo $n
+}
+echo at "44"
+#charmax 
+
+charmaxval=$(charmax "$@")
+echo "$charmaxval"
+
+
+reducedval_char="${charval: -3}"
+#echo "$output"
+echo "${reducedval_char}"
+
+while :                                                            #cat "${filearg}" | while read -r line 
+do
+
+    echo "truncated value: echo  $charval"
+    while ! [[ "${output}" == "M"  &&  $charmaxval -ne 3 ]]  || [[ $charval -lt 53 && ! $charval -gt 54 ]]                     
+    do 
+    echo good 
+    if {
+       count=0
+       while [[ ${count} -le 15 ]]
+         do 
+       echo attempting to download "${filearg}"
+       rsync -vrP -e ssh "${server}"/"*${filearg}*" /home/username/dir/ | tee -a "${logloc}" || true 
+       echo "===================================================" 
+      sleep 2s && wait 
+      ((count ++))
+      returncode=$(echo $?)
+         if [[ $returncode -eq 0 ]]; then 
+         exit 0
+         fi 
+   done 
+     };then
+          exit 0
+    else
+          echo failed to process "${filearg}" | tee -a "${logloc}"
+          exit 1
+    fi
+    done 
+ break 
+  
+ done
+ 
 
