Update scp-transfer-list

diff --git a/scp-transfer-list b/scp-transfer-list
--- a/scp-transfer-list
+++ b/scp-transfer-list
@@ -22,38 +22,35 @@
 
 #!/bin/bash
 
-#set -x
-
-if [[ $@ -eq "-h" ]]; then
+if [[ $@ = "-h" ]]; then
     #echo "-------------------Help Menu-------------------"
     #echo "options:"
-    echo "Options: scp-transfer-list.sh < file-to-read > < dir-path-of-filelist > < target host >"
-    echo "Ex: scp-transfer-list ~/Desktop/filelist.txt /usr/local/bin/ user@hostname:/dirpath"
-elif [[ $# -lt 3 ]]; then 
-    echo "Three arguments are required for this script:"
-    echo "scp-transfer-list.sh < file-to-read > < dir-path-of-filelist > < target host >"
+    echo "Options: scp-transfer-seedbox.sh filelist.txt localdir"
+elif [[ $# -lt 2 ]]; then 
+    echo "Two arguments are required for this script:"
+    echo "Options: scp-transfer-seedbox.sh filelist.txt localdir"
 else
 
-keyfile="/home/richard/.ssh/id_rsa"
-filelist=$1
-filedir=$2
-	
-	while read -r filelist
-	do
-	     for i in $filelist
-	     do
-	        if {
-	            if scp -i $keyfile -r $filedir/"$i" $3; then
-	                echo "Next file..."
-	            else
-	                echo failed to transfer $path
-	            fi
-	            }; then
-	            echo successfully processes scp file: "$i"
-	        else 
-	            echo failed to process scp file: "$i"
-	            exit 1 
-	        fi
-	    done
-	done < $filelist
-fi  
+keyfile="$HOME/username/.ssh/id_rsa" #scp keyfile ... if this is not included, the script will require a password and that will effectively eliminate whatever utility it otherwise had
+filelist="$1"
+#filedir="$2"
+hostarget="gokart@solaris.usbx.me:/home/gokart/downloads/bonbon/"
+targetdir="$2" #local directory - where files go 
+
+while IFS= read -r filename; do
+  # Wrap the filename in double quotes
+  quoted_filename="$(printf "%q" "$filename")"
+
+  if scp -i "$keyfile" -r "$hostarget$quoted_filename" $targetdir; then
+    echo "Successfully transferred file: $filename" | tee -a ~/tmp/scp-transfer-seedbox.log
+elif ! scp -i "$keyfile" -r $hostarget"$quoted_filename" "$targetdir"; then
+    echo "Failed to transfer file: $filename" | tee -a ~/tmp/scp-transfer-seedbox.log
+else 
+    echo "Error: exiting script" | tee -a ~/tmp/scp-transfer-seedbox.log
+    exit 1  
+  fi
+
+done < "$filelist"
+
+fi
+
